theme: jekyll-theme-hacker
title: [Jules Perret ]
description: [Sutend at paris Saclayl university -Code repository]
lsi: false
safe: true
source: [https://github.com/jperret21?tab=repositories]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
