theme: minima
title: [Jules Perret]
description: [ gravitational  Astrophysics Phd student at laboratoire Astroparticule et Cosmologie (APC-CNRS) -Code repository-]
lsi: false
safe: true
source: [jperret21]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
