theme: minima
title: Jules Perret
description: Personnal page 
lsi: false
safe: true
source: jperret21
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
markdown: kramdown

# Navigation
nav:
  - About: /about
  - Research: /research
  - Publications: /publications

collections:
  posts:
    output: True
