theme: jekyll-theme-hacker
title: [Jules Perret ]
description: [IT and math Studend at Paris-Saclayl university -Code repository-]
lsi: false
safe: true
source: [jperret21]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
